### ISSUE TITLE
💡 Create SignUp Screen

### ISSUE THREAD

**Issue by aoiorio** [aoiorio/Volcano#2]
## 🥴 What do you want to do?
- I want to create SignUp Screen
- Also connect to API Endpoints and execute it
<br>

## 🐌 Purpose
- For user experience
<br>

## 🎩 Images
![SignUpPage-mini](https://github.com/aoiorio/Volcano/assets/130330538/cac32ac2-a1f2-44a0-98a8-d83a205dbd0c)

<br>

## 🌋 TODOs
- [x] Create SignUp Screen
- [x] Connect to API Endpoints
- [x] Create API Client for using API Endpoints
