### ISSUE TITLE
💡 Create Privacy Policy & Support URL & Terms Of Service

### ISSUE THREAD

**Issue by aoiorio** [aoiorio/Volcano#48]
## 🥴 What do you want to do?
- I want to create privacy policy, support URL and terms of service
- I want to add them to my app
<br>

## 🐌 Purpose
- for getting acceptance from App Store
<br>

## 🎩 Images
Nothing
<br>

## 🌋 TODOs
- [x] create privacy policy
- [x] create support form (google form)
- [x] create terms of service
- [x] add them to my app (at user modal and sign up page)

**Comment by aoiorio** [comment]
LG   TM
